# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

project_name: envp

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    binary: "{{ .ProjectName }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - format: tar.gz
    wrap_in_directory: "true"
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - "README"
      - "Merge pull request"
      - "Merge branch"

brews:
  - name: "envp"
    tap:
      owner: sunggun-yu
      name: homebrew-tap
      branch: main
    description: "Cli wrapper to set profile based environment variables for your command line execution"
    homepage: https://github.com/sunggun-yu/envp
    folder: Formula
    download_strategy: CurlDownloadStrategy
    install: |
      bin.install "{{ .ProjectName }}"
    test: |
      system "#{bin}/{{ .ProjectName }} -v"
